export type Restaurant = {
    id: string,
    name: string,
    address: string,
    phone: string,
    email: string,
    website: string,
    openingHours: string,
    distance: number,
    cuisine: string,
    vegetarian: boolean,
    vegan: boolean,
    latitude: number,
    longitude: number,
}